# Jekyll Configuration
name: Namito's Standups
description: Script used to update my status during standups
url: "https://standups.namito.wiki"
markdown: GFM
highlighter: rouge
remote_theme: "dracula/gh-pages"
